// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rossko.ElasticWebForm.Data.Model;

#nullable disable

namespace Rossko.ElasticWebForm.Data.Migrations
{
    [DbContext(typeof(OemCatalogDbContext))]
    partial class OemCatalogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Rossko.ElasticWebForm.Data.Model.OemCatalog", b =>
                {
                    b.Property<string>("HitId")
                        .HasColumnType("nvarchar(450)")
                        .UseCollation("SQL_Latin1_General_CP1_CS_AS");

                    b.Property<string>("CarName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CarName");

                    b.Property<string>("Catalog")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Catalog");

                    b.Property<DateTime>("DateIndex")
                        .HasColumnType("Date")
                        .HasColumnName("DateIndex");

                    b.Property<string>("Event")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Event");

                    b.Property<string>("From")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("From");

                    b.Property<bool?>("IsInternalUser")
                        .HasColumnType("bit")
                        .HasColumnName("IsInternalUser");

                    b.Property<bool?>("IsMobile")
                        .HasColumnType("bit")
                        .HasColumnName("IsMobile");

                    b.Property<int?>("MemberId")
                        .HasColumnType("int")
                        .HasColumnName("MemberId");

                    b.Property<DateTime?>("Timestamp")
                        .HasColumnType("datetime2")
                        .HasColumnName("Timestamp");

                    b.Property<string>("VinNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("VinNumber");

                    b.HasKey("HitId")
                        .HasName("HitId");

                    b.HasIndex("DateIndex");

                    b.ToTable("oem_catalog", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
